# Generated by Django 3.2.12 on 2023-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('probability_fradulent', models.PositiveIntegerField()),
            ],
        ),
    ]
