# Generated by Django 3.2.12 on 2023-12-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionProcessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='probability_fradulent',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
