# Generated by Django 3.2.12 on 2023-12-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionProcessor', '0002_alter_reports_probability_fradulent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='batch_no',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
