# Generated by Django 3.2.12 on 2023-12-13 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionProcessor', '0003_reports_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
